version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgreDB
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '!123@123#123'
      POSTGRES_DB: cms_db
    volumes:
      - portainer_data:/var/lib/docker/volumes/portainer_data/_data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./cms-backend
      dockerfile: docker/Dockerfile
    container_name: cms-backend
    restart: always
    environment:
      HOST: '0.0.0.0'
      PORT: 5432
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/media/hugo/aux/cms-project/cms-backend
    command: npm run start:dev

  frontend:
    environment:
      - NEXT_PUBLIC_API_URL=http://82.29.60.183:3001
    build: 
      context: ./cms-frontend
      dockerfile: docker/Dockerfile
    container_name: cms-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/media/hugo/aux/cms-project/cms-frontend
    command: npm run dev

volumes:
  portainer_data:
